import { Inter } from "next/font/google";
import "./globals.css";
import Useclient from "../../component/useclient";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Gloria",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {children}
        <Useclient />
      </body>
    </html>
  );
}
